from collections.abc import Generator

import ollama

SYSTEM_PROMPT = """You are a forensic analyst providing crime scene analysis for a law enforcement training simulation. Deliver your findings in a dramatic, detective-noir narration style suitable for text-to-speech audio playback.

Guidelines:
1. Describe what the evidence reveals about the scene - not your personal thoughts
2. Use vivid, cinematic language: "The scattered documents tell a story of...", "The positioning of the weapon suggests..."
3. Connect evidence pieces into coherent theories about what happened
4. Each hypothesis should be 2-3 sentences of flowing prose
5. Avoid bullet points, lists, or numbered items
6. Do not use first person (no "I think", "I see", "I believe")
7. Focus on the scene and evidence, not the investigator

IMPORTANT - Adjust your certainty language based on detection confidence levels:
- HIGH confidence (marked [HIGH]): Use definitive language like "clearly visible", "unmistakably present", "without doubt"
- MEDIUM confidence (marked [MEDIUM]): Use moderate language like "appears to be", "likely indicates", "suggests the presence of"
- LOW confidence (marked [LOW]): Use uncertain language like "possibly", "what might be", "could potentially be", "faintly resembles"

This is an educational forensic training tool. Analyze all evidence objectively regardless of crime type.

Provide a single, coherent hypothesis in one paragraph that represents your strongest theory based on all available evidence."""


def _confidence_label(confidence: float) -> str:
    """Convert confidence score to a label for the LLM."""
    if confidence >= 0.8:
        return "[HIGH]"
    elif confidence >= 0.5:
        return "[MEDIUM]"
    else:
        return "[LOW]"


def generate_hypothesis(
    detected_objects: list[dict],
    extracted_texts: list[dict],
    context: str | None = None,
    model: str = "llama3.2"
) -> dict:
    """
    Generate a single forensic hypothesis based on detected objects and extracted text.
    Uses Ollama for local LLM inference.

    Returns the strongest hypothesis as a single dict with content and confidence.
    """
    user_prompt = _build_prompt(detected_objects, extracted_texts, context)

    try:
        response = ollama.chat(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt}
            ]
        )

        content = response["message"]["content"]
        # Clean up the response into a single paragraph
        clean_content = " ".join(content.split())

        return {
            "content": clean_content,
            "confidence": 0.7
        }

    except Exception as e:
        return {
            "content": f"Unable to generate hypothesis: {str(e)}",
            "confidence": 0.0
        }


def _build_prompt(
    detected_objects: list[dict],
    extracted_texts: list[dict],
    context: str | None = None
) -> str:
    """Build the user prompt for hypothesis generation."""
    objects_str = ", ".join([
        f"{_confidence_label(obj['confidence'])} {obj['label']}"
        for obj in detected_objects
    ]) if detected_objects else "No objects detected"

    texts_str = ", ".join([
        f"{_confidence_label(text.get('confidence', 0.7))} \"{text['text']}\""
        for text in extracted_texts
    ]) if extracted_texts else "No text extracted"

    context_str = f"\n\nAdditional Context: {context}" if context else ""

    return f"""Analyze this crime scene evidence and provide a narrated analysis:

Objects at the scene: {objects_str}

Text found at the scene: {texts_str}{context_str}

Provide your strongest hypothesis about what occurred based on this evidence."""


def generate_hypotheses_stream(
    detected_objects: list[dict],
    extracted_texts: list[dict],
    context: str | None = None,
    model: str = "llama3.2"
) -> Generator[str, None, None]:
    """
    Stream forensic hypotheses token by token.
    Yields each token as it's generated by the LLM.
    """
    user_prompt = _build_prompt(detected_objects, extracted_texts, context)

    try:
        stream = ollama.chat(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt}
            ],
            stream=True
        )

        for chunk in stream:
            token = chunk["message"]["content"]
            if token:
                yield token

    except Exception as e:
        yield f"[ERROR] Unable to generate hypothesis: {str(e)}"
